### ISSUE TITLE
Criar Tabela Usuário

### ISSUE THREAD

**Issue by ab-vitor** [MrAlves17/Defesas-de-TCC#17]
Tabela especificada no diagrama de banco de dados.

**Comment by MatheusOCC** [comment]
Script de criação pode ser visto no sqlite com o comando ".schema"

CREATE TABLE Usuario 
(
idUsuario INT NOT NULL PRIMARY KEY, 
nomeUsuario VARCHAR(50) NOT NULL, 
statusUsuario VARCHAR(255) NOT NULL, 
senha VARCHAR(45) NOT NULL, 
matricula VARCHAR(45) NOT NULL, 
email VARCHAR(255) NOT NULL, 
idPerfil INT NOT NULL, 
FOREIGN KEY(idPerfil) REFERENCES Perfil(idPerfil)
);

**Comment by MatheusOCC** [comment]
Reaberta pois ainda não foi testada a PBI
