### ISSUE TITLE
Criar Tabela Perfil

### ISSUE THREAD

**Issue by ab-vitor** [MrAlves17/Defesas-de-TCC#20]

**Comment by MatheusOCC** [comment]
Script de criação pode ser visto no sqlite com o comando ".schema"

CREATE TABLE PERFIL
(
idPerfil INT NOT NULL PRYMARY KEY,
nomePerfil VARCHAR (50) NOT NULL UNIQUE
)

**Comment by MatheusOCC** [comment]
Script de criação pode ser visto no sqlite com o comando ".schema"

CREATE TABLE PERFIL
(
idPerfil INT NOT NULL PRYMARY KEY,
nomePerfil VARCHAR (50) NOT NULL UNIQUE
)

**Comment by MatheusOCC** [comment]
Script de criação pode ser visto no sqlite com o comando ".schema"

CREATE TABLE PERFIL
(
idPerfil INT NOT NULL PRYMARY KEY,
nomePerfil VARCHAR (50) NOT NULL UNIQUE
)

**Comment by MatheusOCC** [comment]
Reaberta pois ainda não foi testada a PBI
